amlgrep: add --ignore-case and --dump option

diff --git a/amlgrep b/amlgrep
--- a/amlgrep
+++ b/amlgrep
@@ -11,33 +11,34 @@
 #
 print_help () {
 cat <<EOF
-Usage: $0 [--or|--and] [--] PATTERNS... [--] [FILES...]
-  grep like tool to search multi-line log entries separated by '-----------'.
-  In reality, just an awk wrapper with RS='\\n-----------\\n' and IFS='\\n'
-  If an argument is an existing file or '-' (means standard input) or '--',
-  the argument and everything after that will be treated as filenames to read
-  from. (If you just want to search literal '-' or '--', use '[-]' or '-{2}')
-  If file name is *.gz, *.bz2 or *.xz, uncompress it on-the-fly before
+Usage: $0 [OPTIONS] [--] PATTERNS... [--] [FILES...]
+  grep like tool to search multi-line log separated by '$opt_RS'.
+  (--rs option to change this) In reality, just an awk wrapper with
+  RS='$opt_RS', ORS='$opt_ORS' and IFS='\\n')
+  If an argument is a name of existing file or '-', that argument and
+  everything after that will be treated as filenames to read from.
+  If file name ends with .gz, .bz2 or .xz, uncompress it on-the-fly before
   reading from it.
 OPTIONS
-  -h, --help  Print this help.
-  -o, --or    Print entries match with any of PATTERNS. This is the default.
-  -a, --and   Print entries match with all of PATTERNS.
-  -c, --count Print number of matches.
-  --color
-  -m, --mono  Highlight or do not matches. Default is to highlight matches if
-              standard out is a terminal.
-  -v, --invert-match
-        Select non-matching lines.
-  -r, --rs, --record-separator
-        Set input record separater. Default is "$opt_RS"
-  --ors, --output-record-separator
-        Set output record separater. Default is "$opt_ORS"
+  -h, --help            Print this help.
+  -v, --invert-match    Select non-matching lines (same as grep -v).
+  -i, --ignore-case     Case-insensitive match (same as grep -i).
+  -c, --count           Print number of matches.
+  --color, -m, --mono   (Do not) Highlight matches.
+        (Default is to highlight matches if standard out is a terminal.)
+  -a, --and   Print entries match with all, instead of any, of PATTERNS.
+  -r, --rs    Set input record separater. Default is "$opt_RS"
+  --ors       Set output record separater. Default is "$opt_ORS"
+  --dump      Dump the awk commands that would be executed.
+BUGS
+  --ignore-case option only works when gawk is available on your system,
+  and it also affects how regex for --rs option is interpreted.
 EOF
 }
 
 set -eu
 
+DIE () { echo "$0: ERROR: $*" >&2; exit 1; }
 
 #################################################################
 ##
@@ -72,8 +73,7 @@ then
         #awk_type='awk'
     fi
 else
-    echo "$0: ERROR: awk is not found (missing \$PATH ?)"
-    exit 1
+    DIE "ERROR: awk is not found (missing \$PATH ?)"
 fi
 
 #case $awk_type in
@@ -90,8 +90,10 @@ opt_conjunction='OR'
 opt_invert='no'
 opt_count='no'
 opt_color='auto'
-opt_RS='\n----------------*\n'
-opt_ORS='\n----------------\n'
+opt_ignorecase='no'
+opt_RS='\n--------*\n'
+opt_ORS='\n--------\n'
+opt_dump='no'
 while [ $# -ge 1 ]
 do
 case $1 in
@@ -105,11 +107,13 @@ case $1 in
     -o|--or)  opt_conjunction='OR';;
     -a|--and) opt_conjunction='AND';;
     -v|--invert|--invert-match) opt_invert='yes';;
+    -c|--count) opt_count='yes';;
+    -i|--ignore-case) opt_ignorecase='yes';;
     -r|--rs|--record-separator) opt_RS="$2"; shift;;
     --ors|--output-record-separator) opt_ORS="$2"; shift;;
-    -c|--count) opt_count='yes';;
     --color) opt_color='always';;
     --mono) opt_color='never';;
+    --dump) opt_dump='yes';;
     #------------------------------------------
     -h|--help) print_help; exit 0;;
     --) shift; break;;
@@ -128,6 +132,17 @@ awkargs=(-F "$IFS" -v RS="$RS" -v ORS="$ORS")
 if [ $# -lt 1 ]; then
     print_help
     exit 1
+fi
+
+if [ "$opt_ignorecase" = 'yes' ]
+then
+    if [ "$awk_type" = 'gawk' ]
+    then
+        awkargs+=('-v' 'IGNORECASE=1')
+    else
+        DIE "-i (--ignore-case) option needs gawk. " \
+            "Your awk on this system is: '$awk'"
+    fi
 fi
 
 if [ "$opt_color" = 'always' -o "$opt_color" = 'auto' -a -t 1 ]
@@ -192,12 +207,21 @@ fi
 # read from stdin ("-") if no file name is given
 [ $# -eq 0 ] && set -- "-"
 
-for file in "$@"
-do
-    case "$file" in
-        *.gz)  gunzip -c "$file";;
-        *.bz2) bzcat "$file";;
-        *.xz)  xzcat "$file";;
-        *)     cat "$file";;
-    esac | $awk "${awkargs[@]}" "$awkstatement"
-done
+if [ "$opt_dump" = 'yes' ]
+then
+    for arg in "$awk" "${awkargs[@]}" "$awkstatement"
+    do
+        echo "$arg"
+    done | xargs -d'\n' -I{} -n1 echo -n "'{}' "
+    echo
+else
+    for file in "$@"
+    do
+        case "$file" in
+            *.gz)  gunzip -c "$file";;
+            *.bz2) bzcat "$file";;
+            *.xz)  xzcat "$file";;
+            *)     cat "$file";;
+        esac | $awk "${awkargs[@]}" "$awkstatement"
+    done
+fi
